#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

if [ "$CURATOR_ENABLED" = "yes" ]; then
        echo -n "so-curator: "
        if docker ps | grep -q so-curator; then
                echo "Already started!"
        else

		CONFIG="/etc/curator/config/curator.yml"
		# If Elastic auth is enabled, then make sure Curator is configured to authenticate to Elasticsearch
		if [ -f $ELASTICSEARCH_ACCOUNTS ]; then
			ELASTIC_PASSWORD=$(grep "PASSWORD elastic = " $ELASTICSEARCH_ACCOUNTS | awk '{print $4}')
			sed -i "s|^  http_auth: .*$|  http_auth: elastic:$ELASTIC_PASSWORD|" $CONFIG
			chown curator:curator $CONFIG
			chmod 640 $CONFIG
		fi

		docker rm so-curator >/dev/null 2>&1

		# No published ports
                docker run --name=so-curator \
                        --detach \
                        --volume /etc/curator/config/curator.yml:/etc/curator/config/curator.yml:ro \
                        --volume /etc/curator/action/:/etc/curator/action:ro \
                        --volume /var/log/curator/:/var/log/curator/ \
                        -it \
                        $CURATOR_OPTIONS \
                        $DOCKERHUB/so-curator

		# curator connects to elasticsearch over $DOCKERNET
		docker network connect --alias curator $DOCKERNET so-curator
        fi
fi
