#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

if [ "$DOMAIN_STATS_ENABLED" = "yes" ]; then
        echo -n "so-domainstats: "
        if docker ps | grep -q so-domainstats; then
                echo "Already started!"
        else
		docker rm so-domainstats >/dev/null 2>&1
		# No published ports
                docker run --name=so-domainstats \
                        --detach \
                        --volume /var/log/domain_stats:/var/log/domain_stats \
                        $DOMAIN_STATS_OPTIONS \
                        $DOCKERHUB/so-domainstats

		# Logstash will connect to DomainStats over $DOCKERNET
		docker network connect --alias domainstats $DOCKERNET so-domainstats
        fi
fi

