#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

# Configure firewall
/usr/sbin/so-elastic-configure-ufw

echo
echo "Starting containers:"
echo

# Start so-freqserver
. /usr/sbin/so-freqserver-start

# Start so-domainstats
. /usr/sbin/so-domainstats-start

# Start so-elasticsearch
. /usr/sbin/so-elasticsearch-start

# Start so-kibana
. /usr/sbin/so-kibana-start

# Start so-logstash
. /usr/sbin/so-logstash-start

# Start so-elastalert
. /usr/sbin/so-elastalert-start

# Start so-curator
. /usr/sbin/so-curator-start

echo
