#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

# Need to remove the existing containers before starting new ones.
# so-elastic-stop does run so-elastic-remove after stopping containers,
# but we need to run it again here just in case.
# The common scenario would be a user rebooting without first
# running so-elastic-stop.
/usr/sbin/so-elastic-remove

# Configure firewall
/usr/sbin/so-elastic-configure-ufw

echo
echo "Starting containers:"
echo

# Start so-freqserver
. /usr/sbin/so-freqserver-start

# Start so-domainstats
. /usr/sbin/so-domainstats-start

# Start so-elasticsearch
. /usr/sbin/so-elasticsearch-start

# Start so-logstash
. /usr/sbin/so-logstash-start

# Start so-kibana
. /usr/sbin/so-kibana-start

# Start so-elastalert
. /usr/sbin/so-elastalert-start

# Start so-curator
. /usr/sbin/so-curator-start

echo
