#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

if [ "$ELASTALERT_ENABLED" = "yes" ]; then
        echo -n "so-elastalert: "
        if docker ps | grep -q so-elastalert; then
                echo "Already started!"
        else
		docker rm so-elastalert >/dev/null 2>&1
		# No published ports
                docker run --name=so-elastalert \
                        --detach \
                        --volume /etc/elastalert/rules:/etc/elastalert/rules/ \
                        --volume /var/log/elastalert:/var/log/elastalert/ \
                        $ELASTALERT_OPTIONS \
                        $DOCKERHUB/so-elastalert

		# ElastAlert will connect to Elasticsearch over $DOCKERNET
		docker network connect --alias elastalert $DOCKERNET so-elastalert
        fi
fi
