#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

# If Elasticsearch is not enabled, then exit immediately
[ "${ELASTICSEARCH_ENABLED}" != "yes" ]	&& exit

# Build a list of enabled services
LIST="so-elasticsearch"
[ "${LOGSTASH_ENABLED}" == "yes" ]         && LIST="$LIST so-logstash"
[ "${KIBANA_ENABLED}" == "yes" ]           && LIST="$LIST so-kibana"
[ "${ELASTALERT_ENABLED}" == "yes" ]       && LIST="$LIST so-elastalert"
[ "${CURATOR_ENABLED}" == "yes" ]          && LIST="$LIST so-curator"
[ "${FREQ_SERVER_ENABLED}" == "yes" ]       && LIST="$LIST so-freqserver"
[ "${DOMAIN_STATS_ENABLED}" == "yes" ]      && LIST="$LIST so-domainstats"
docker stats $LIST $@
