#!/bin/bash

. /usr/sbin/so-elastic-common
. /etc/nsm/securityonion.conf

CURATOR_DEL="/etc/curator/action/delete.yml"

if [ -f $CURATOR_DEL ]; then
        sed -i "s/disk_space:.*/disk_space: $LOG_SIZE_LIMIT/" $CURATOR_DEL
fi
