#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

if [ "${KIBANA_ENABLED}" = "no" ]; then

	header "Kibana is disabled, skipping shortcut config"

else

	header "Replacing ELSA shortcuts with Kibana shortcuts"
	for i in /home/*/Desktop /etc/skel/Desktop /usr/share/applications; do
        	echo "Checking $i"
	        ELSA="$i/securityonion-elsa.desktop"
        	KIBANA="$i/securityonion-kibana.desktop"
	        if [ -f $ELSA ]; then
        	        echo "Renaming $ELSA to $KIBANA"
                	mv $ELSA $KIBANA
	                echo "Updating $KIBANA"
        	        sed -i 's|Name=ELSA|Name=Kibana|g' $KIBANA
                	sed -i 's|https://localhost/elsa|https://localhost/app/kibana|g' $KIBANA
	        fi
	done
	echo "Done!"

fi
