#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

/usr/sbin/so-redis-stop

if docker ps | grep -q so- ; then
	echo
	echo "Stopping containers:"
	echo

	/usr/sbin/so-logstash-stop

	/usr/sbin/so-kibana-stop

	/usr/sbin/so-elasticsearch-stop

	/usr/sbin/so-elastalert-stop

	/usr/sbin/so-curator-stop

	/usr/sbin/so-freqserver-stop

	/usr/sbin/so-domainstats-stop
else
	echo
	echo "Containers already stopped!"
	echo
fi
