#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

if [ "$ELASTALERT_ENABLED" = "yes" ]; then
        echo -n "so-elastalert: "
        if docker ps | grep -q so-elastalert; then
                echo "Already started!"
        else
		# No published ports
                docker run --name=so-elastalert \
                        --detach \
                        --network-alias=elastalert \
                        --network="${DOCKERNET}" \
                        --volume /etc/elastalert/rules:/etc/elastalert/rules/ \
                        --volume /var/log/elastalert:/var/log/elastalert/ \
                        $ELASTALERT_OPTIONS \
                        $DOCKERHUB/so-elastalert
        fi
fi
