#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

FILE="/etc/logrotate.d/kibana"

if ! [ -f ${FILE} ]; then

	cat << EOF > ${FILE}
/var/log/kibana/kibana.log {
    daily
    rotate 7
    copytruncate
    compress
    missingok
    notifempty
    sharedscripts
    postrotate
	/usr/sbin/so-kibana-reload
    endscript
}
EOF

fi
