#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

[ "$LOGSTASH_OUTPUT_REDIS" = "yes" ] && pgrep redis-server >/dev/null 2>&1 && service redis-server stop

if docker ps | grep -q so- ; then
	echo
	echo "Stopping containers:"
	echo
	[ "$LOGSTASH_ENABLED" = "yes" ] && docker ps | grep -q so-logstash && docker stop so-logstash 
	[ "$KIBANA_ENABLED" = "yes" ] && docker ps | grep -q so-kibana && docker stop so-kibana
	[ "$ELASTICSEARCH_ENABLED" = "yes" ] && docker ps | grep -q so-elasticsearch && docker stop so-elasticsearch
	[ "$ELASTALERT_ENABLED" = "yes" ] && docker ps | grep -q so-elastalert && docker stop so-elastalert
	[ "$CURATOR_ENABLED" = "yes" ] && docker ps | grep -q so-curator && docker stop so-curator
	[ "$FREQ_SERVER_ENABLED" = "yes" ] && docker ps | grep -q so-freqserver && docker stop so-freqserver
	[ "$DOMAIN_STATS_ENABLED" = "yes" ] && docker ps | grep -q so-domainstats && docker stop so-domainstats
	echo
	echo "Removing containers:"
	echo
else
	echo
	echo "Containers already stopped!"
	echo
fi

/usr/sbin/so-elastic-remove
