#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common
. /etc/nsm/securityonion.conf

# If Elasticsearch is not enabled, then exit immediately
[ "$ELASTICSEARCH_ENABLED" != "yes" ] && exit

SKIP=0

#########################################
# Options
#########################################
usage()
{
cat <<EOF
Security Onion Elastic Reset
  Options:
  -h         This message
  -y         Skip interactive mode

EOF
}

while getopts "h:y" OPTION
do
        case $OPTION in
                h)
                        usage
                        exit 0
                        ;;
                y)
                        SKIP=1
                        ;;
                *)
                        usage
                        exit 0
                        ;; 
        esac
done

if [ $SKIP -ne 1 ]; then

	# List indices
	echo
	curl -XGET "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/_cat/indices?v&pretty"
	echo

	# Inform user we are about to delete all data
	echo
	echo "This script will delete all data (documents, indices, etc.) in the Elasticsearch database."
	echo
	echo "If you would like to proceed, please type "AGREE" and hit ENTER."
	echo

	# Read user input
	read INPUT
	if [ "$INPUT" != "AGREE" ] ; then exit 0; fi
fi

# Stop syslog-ng
echo
service syslog-ng stop
echo

# Restart bro to clear logs
echo
/usr/sbin/so-bro-restart > /dev/null 2>&1
echo

# Delete data
echo "Deleting data..."
INDXS=$(curl -s -XGET ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/_cat/indices?v | egrep 'logstash|elastalert' | awk '{ print $3 }')
for INDX in ${INDXS}
do
    curl -XDELETE "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/${INDX}" > /dev/null 2>&1
done

# Start syslog-ng
echo
service syslog-ng start
echo

# Message to user
echo
echo "All Elasticsearch data has been deleted."
echo
