#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

if [ ${ELASTALERT_ENABLED} = "yes" ]; then

	header "Configuring ElastAlert"

	# We need to wait for ElastAlert to initialize all its indices (elastalert_status_past is the last one)
	MAX_WAIT=240
	while curl -s -XGET http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/elastalert_status_past | grep -q "no such index" ; do
		wait_step=$(( ${wait_step} + 1 ))
		if [ ${wait_step} -gt ${MAX_WAIT} ]; then
			echo "ERROR: Elasticsearch not available for more than ${MAX_WAIT} seconds."
			exit 5
		fi
		sleep 1s;
	done
	
	# Disable replicas so that ES status will show green
        curl -s -XPUT "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/elastalert*/_settings" \
             -H 'Content-Type: application/json' \
             -d'{"index" : {"number_of_replicas" : 0}}'
	echo

else
	echo "ElastAlert disabled, so not configuring..."
fi
