#!/bin/bash
. /usr/lib/nsmnow/lib-console-utils
. /etc/nsm/securityonion.conf

function ok(){
	echo -ne "$STAT[${GREEN_BOLD}  OK  ${NORMAL}]"
}
function fail(){
	echo -ne "$STAT[${RED_BOLD} FAIL ${NORMAL}]"
}
function warn(){
	echo -ne "$STAT[${YELLOW_BOLD} WARN ${NORMAL}]"
}

# If Elasticsearch is not enabled, then exit immediately
[ "$ELASTICSEARCH_ENABLED" != "yes" ] && exit

echo -ne "${BLUE_BOLD}Status: Elastic stack${NORMAL}"
echo

if [ "$ELASTICSEARCH_ENABLED" = "yes" ]; then
	echo -ne "  ${BLUE}*${NORMAL} so-elasticsearch"
	if docker ps |  grep -q so-elasticsearch; then
		ok
	else
		fail
	fi
fi

if [ "$LOGSTASH_ENABLED" = "yes" ]; then
	QUEUE_TYPE=$(curl -s "$LOGSTASH_HOST:$LOGSTASH_PORT/_node/stats" | jq .pipelines.main.queue.type | sed s/\"//g)
	echo -ne "   ${BLUE}*${NORMAL} so-logstash"
	if docker ps |	grep -q so-logstash; then
		if [ "$QUEUE_TYPE" == "memory" ] || [ "$QUEUE_TYPE" == "persisted" ]; then	
			ok
		else
			echo " -- Logstash has started, but is still initializing...$(warn)"
		fi
	else
		fail
	fi
fi

if [ "$KIBANA_ENABLED" = "yes" ]; then
	echo -ne "   ${BLUE}*${NORMAL} so-kibana"
	if docker ps |  grep -q so-kibana; then
                ok
        else
                fail
        fi
fi

if [ "$FREQ_SERVER_ENABLED" = "yes" ]; then
	echo -ne "   ${BLUE}*${NORMAL} so-freqserver"	
	if docker ps |  grep -q so-freqserver; then
                ok
        else
                fail
        fi
fi

if [ "$DOMAIN_STATS_ENABLED" = "yes" ]; then
	echo -ne "   ${BLUE}*${NORMAL} so-domainstats"
	if docker ps |  grep -q so-domainstats; then
		ok
        else
		fail
        fi
fi

if [ "$CURATOR_ENABLED" = "yes" ]; then
	echo -ne "   ${BLUE}*${NORMAL} so-curator"
	if docker ps |  grep -q so-curator; then
		ok
        else
		fail
        fi
fi

if [ "$ELASTALERT_ENABLED" = "yes" ]; then
	echo -ne "   ${BLUE}*${NORMAL} so-elastalert"
        if docker ps |  grep -q so-elastalert; then
		ok
	else
		fail
        fi
fi

if [ "$LOGSTASH_OUTPUT_REDIS" = "yes" ]; then
	echo -ne "   ${BLUE}*${NORMAL} redis"
        if pgrep redis-server > /dev/null; then
		ok
	else
		fail
        fi
fi

echo
