#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Originally written by Bryant Treacle
# https://raw.githubusercontent.com/bryant-treacle/so-elastalert-test-rule/master/so-elastalert-test
# Modified by Doug Burks
#
# Purpose:  This script will allow you to test your elastalert rule without entering the Docker container.

. /usr/sbin/so-elastic-common

# This script now optionally accepts two command line arguments ($1 and $2):
# $1 - the Elastalert rule that you want to test
# $2 - the file that you want to save output to
# If one or both of these optional parameters are omitted, we will prompt the user for input.

if [ -z "$1" ]; then
	echo
	echo "This script will allow you to test an Elastalert rule."
	echo
	echo "Below is a list of active rules in the /etc/elastalert/rules/ directory."
	echo 
	# piping ls to cat to emulate original behavior of one file per line
	ls /etc/elastalert/rules/ | cat
	echo 
	echo "Note: To test a rule it must be accessible by the Elastalert docker container."
	echo
	echo "Please enter the file path and rule name you want to test."
	read -e TEST_RULE
else
	TEST_RULE=$1
fi

if [ -z "$2" ]; then
	echo
	echo "The results can be rather long."
	echo "If you would like to write the results to a file, please enter the filename."
	echo "Otherwise, just press the Enter key."
	read FILE_SAVE_LOCATION
else
	FILE_SAVE_LOCATION=$2
fi

if [ -z ${FILE_SAVE_LOCATION} ] ; then
	docker exec -it so-elastalert bash -c "elastalert-test-rule $TEST_RULE"
else
	echo
	echo "Depending on the rule this may take a while."
	docker exec -it so-elastalert bash -c "elastalert-test-rule $TEST_RULE" > ${FILE_SAVE_LOCATION}
	OUTPUT="You can check the output in ${FILE_SAVE_LOCATION}."
fi

echo
echo "Complete! ${OUTPUT}"
