#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

header "Reconfiguring syslog-ng to send logs to Elastic"
FILE="/etc/syslog-ng/syslog-ng.conf"
cp $FILE $FILE.bak
if ! grep -q 'destination d_logstash' $FILE; then
        sed -i '/^destination d_elsa/a destination d_logstash { tcp("127.0.0.1" port(6050) template("$(format-json --scope selected_macros --scope nv_pairs --exclude DATE --key ISODATE)\\n")); };' $FILE
fi
sed -i 's/log { destination(d_elsa); };/log { destination(d_logstash); };/' $FILE
sed -i '/rewrite(r_host);/d' $FILE
sed -i '/rewrite(r_cisco_program);/d' $FILE
sed -i '/rewrite(r_snare);/d' $FILE
sed -i '/rewrite(r_from_pipes);/d' $FILE
sed -i '/rewrite(r_pipes);/d' $FILE
sed -i '/parser(p_db);/d' $FILE
sed -i '/rewrite(r_extracted_host);/d' $FILE
if ! grep s_bro_dce_rpc $FILE >/dev/null 2>&1; then
        sed -i '/^source s_bro_sip/a source s_bro_dce_rpc { file("/nsm/bro/logs/current/dce_rpc.log" flags(no-parse) program_override("bro_dce_rpc")); };' $FILE
        sed -i '/source(s_bro_ssh);/a \\tsource(s_bro_dce_rpc);' $FILE
fi
if ! grep s_bro_ntlm $FILE >/dev/null 2>&1; then
        sed -i '/^source s_bro_sip/a source s_bro_ntlm { file("/nsm/bro/logs/current/ntlm.log" flags(no-parse) program_override("bro_ntlm")); };' $FILE
        sed -i '/source(s_bro_ssh);/a \\tsource(s_bro_ntlm);' $FILE
fi
if ! grep s_bro_smb_files $FILE >/dev/null 2>&1; then
        sed -i '/^source s_bro_sip/a source s_bro_smb_files { file("/nsm/bro/logs/current/smb_files.log" flags(no-parse) program_override("bro_smb_files")); };' $FILE
        sed -i '/source(s_bro_ssh);/a \\tsource(s_bro_smb_files);' $FILE
fi
if ! grep s_bro_smb_mapping $FILE >/dev/null 2>&1; then
        sed -i '/^source s_bro_sip/a source s_bro_smb_mapping { file("/nsm/bro/logs/current/smb_mapping.log" flags(no-parse) program_override("bro_smb_mapping")); };' $FILE
        sed -i '/source(s_bro_ssh);/a \\tsource(s_bro_smb_mapping);' $FILE
fi

# If syslog-ng is still configured for old OSSEC logs, migrate to Wazuh JSON format
if grep "/var/ossec/logs/archives/archives.log" $FILE >/dev/null 2>&1; then
	sed -i "s|source s_ossec { file(\"/var/ossec/logs/archives/archives.log\" program_override('ossec_archive') follow_freq(1) flags(no-parse)); };|source s_ossec { file(\"/var/ossec/logs/alerts/alerts.json\" program_override(\"ossec\") follow_freq(1) flags(no-parse)); };\nsource s_ossec_archive { file(\"/var/ossec/logs/archives/archives.json\" program_override(\"ossec_archive\") follow_freq(1) flags(no-parse)); };|g" $FILE
	sed -i "s|source(s_ossec);|source(s_ossec);\n\tsource(s_ossec_archive);|g" $FILE
fi

# securityonion-elastic: remove Wazuh's alerts.json from syslog-ng config #1467
# https://github.com/Security-Onion-Solutions/security-onion/issues/1467
if grep -q "/var/ossec/logs/alerts/alerts.json" $FILE ; then

	# change source s_ossec from alerts.json to archives.json
	sed -i 's|source s_ossec { file("/var/ossec/logs/alerts/alerts.json" program_override("ossec") follow_freq(1) flags(no-parse)); };|source s_ossec { file("/var/ossec/logs/archives/archives.json" program_override("ossec") follow_freq(1) flags(no-parse)); };|g' $FILE

	# delete s_ossec_archive
	sed -i '|source s_ossec_archive { file("/var/ossec/logs/archives/archives.json" program_override("ossec_archive") follow_freq(1) flags(no-parse)); };|d' $FILE
	sed -i '|source(s_ossec_archive);|d' $FILE

fi

service syslog-ng restart
echo "Done!"
