#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-common

SO_CONF="/etc/nsm/securityonion.conf"
ELSA_CONF="/etc/elsa_node.conf"

header "Migrating ELSA log_size_limit value"
if [ -f $ELSA_CONF ]; then
	LOG_SIZE_LIMIT=$(grep 'log_size_limit' $ELSA_CONF | grep -v '#' | cut -d: -f2 | sed 's/ //' | sed 's/,//')
	LOG_SIZE_LIMIT_GB=$(($LOG_SIZE_LIMIT/1000000000))
	if ! grep -q LOG_SIZE_LIMIT $SO_CONF; then
		cat << EOF >> $SO_CONF

# Log size limit (GB) for Elasticsearch logs
LOG_SIZE_LIMIT=$LOG_SIZE_LIMIT_GB
EOF
		else
			sed "s/LOG_SIZE_LIMIT=.*/LOG_SIZE_LIMIT=$LOG_SIZE_LIMIT_GB/" $SO_CONF
		fi
	echo "Done!"
else
	echo "No ELSA configuration file found!  Exiting..."
fi
