#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf
if docker ps -f "status=exited" | grep -q so- ; then
	[ "$ELASTICSEARCH_ENABLED" = "yes" ] && docker rm so-elasticsearch 2>&1 | grep -v "No such container"
	[ "$LOGSTASH_ENABLED" = "yes" ] && docker rm so-logstash 2>&1 | grep -v "No such container"
	[ "$KIBANA_ENABLED" = "yes" ] && docker rm so-kibana 2>&1 | grep -v "No such container"
	[ "$ELASTALERT_ENABLED" = "yes" ] && docker rm so-elastalert 2>&1 | grep -v "No such container"
	[ "$CURATOR_ENABLED" = "yes" ] && docker rm so-curator 2>&1 | grep -v "No such container"
	[ "$FREQ_SERVER_ENABLED" = "yes" ] && docker rm so-freqserver 2>&1 | grep -v "No such container"
	[ "$DOMAIN_STATS_ENABLED" = "yes" ] && docker rm so-domainstats 2>&1 | grep -v "No such container"
fi
