#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-common

ELASTICDIR="/opt/elastic"
mkdir -p $ELASTICDIR
cd $ELASTICDIR
SRC="$ELASTICDIR/src"

DOCKERHUB="securityonionsolutions"

ELASTICDOWNLOADCONF="/etc/nsm/elasticdownload.conf"
if ! grep "DOCKERHUB" $ELASTICDOWNLOADCONF >/dev/null 2>&1; then
cat << EOF >> $ELASTICDOWNLOADCONF
# Our docker images are hosted on Docker Hub:
# https://hub.docker.com/u/securityonionsolutions/
DOCKERHUB="$DOCKERHUB"
EOF
fi

[ -f $ELASTICDOWNLOADCONF ] && . $ELASTICDOWNLOADCONF

ELASTICSEARCH_AUTH=""
ELASTICSEARCH_ACCOUNTS="/etc/elasticsearch/elasticsearch_accounts"
if [ -f $ELASTICSEARCH_ACCOUNTS ]; then
	ELASTICSEARCH_USERNAME="elastic"
	ELASTICSEARCH_PASSWORD=$(grep "PASSWORD elastic = " $ELASTICSEARCH_ACCOUNTS | awk '{print $4}')
	ELASTICSEARCH_AUTH="-u $ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD"
fi
