#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

/usr/sbin/so-redis-stop

if docker ps | grep -q so- ; then
	echo
	echo "Stopping containers:"
	echo

	/usr/sbin/so-logstash-stop

	/usr/sbin/so-kibana-stop

	/usr/sbin/so-elasticsearch-stop

	/usr/sbin/so-elastalert-stop

	/usr/sbin/so-curator-stop

	/usr/sbin/so-freqserver-stop

	/usr/sbin/so-domainstats-stop
else
	echo
	echo "Containers already stopped!"
	echo
fi
