#!/bin/bash

. /usr/sbin/so-elastic-common
. /etc/nsm/securityonion.conf

header "Configuring Curator"
. /usr/sbin/so-elastic-configure-curator-delete
. /usr/sbin/so-elastic-configure-curator-close
echo "Done!"
