#!/bin/bash

. /usr/sbin/so-elastic-common

if [ "${KIBANA_ENABLED}" = "no" ]; then

	echo "Kibana is disabled, skipping config"

else

	. /usr/sbin/so-elastic-configure-kibana-config

	. /usr/sbin/so-elastic-configure-kibana-dashboards

	. /usr/sbin/so-elastic-configure-kibana-shortcuts

fi
