#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

if [ ${ELASTALERT_ENABLED} = "yes" ]; then

	header "Configuring ElastAlert"

	# We need to wait for ElastAlert to initialize indices
	MAX_WAIT=240
	while curl -s -XGET http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/elastalert_status | grep -q "no such index" ; do
		wait_step=$(( ${wait_step} + 1 ))
		if [ ${wait_step} -gt ${MAX_WAIT} ]; then
			echo "ERROR: Elasticsearch not available for more than ${MAX_WAIT} seconds."
			exit 5
		fi
		sleep 1s;
	done
	
	# Disable replicas so that ES status will show green
        curl -s -XPUT "${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/elastalert*/_settings" \
             -H 'Content-Type: application/json' \
             -d'{"index" : {"number_of_replicas" : 0}}'
	echo

else
	echo "ElastAlert disabled, so not configuring..."
fi
