#!_bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Originally written by Bryant Treacle
# https://raw.githubusercontent.com/bryant-treacle/so-elastalert-test-rule/master/so-elastalert-test
# Modified by Doug Burks
#
# Purpose:  This script will allow you to test your elastalert rule without entering the Docker container.

. /usr/sbin/so-elastic-common

options=""
skip=0
resultstolog="n"

usage()
{
cat <<EOF

Test Elastalert Rule
  Options:
  -h         		This message
  -a         		Trigger real alerts instead of the debug alert
  -l <path_to_file      Write results to specified log file
  -o '<options>'	Specify Elastalert options ( Ex. --schema-only , --count-only, --days N )
  -r <rule_name>        Specify path/name of rule to test

EOF
}

while getopts "hal:o:r:" OPTION
do
        case $OPTION in
                h)
                        usage
                        exit 0
                        ;;
                a)
                        options="--alert"
                        ;;
                l)
                        resultstolog="y"
                        filesavelocation=$OPTARG
                        ;;

                o)
			options=$OPTARG
                        ;;

                r)
                        rulename=$OPTARG
                        skip=1
                        ;;
                *)
                        usage
                        exit 0
                        ;;
        esac
done

docker_exec(){
	if [ ${resultstolog,,} = "y" ] ; then
		docker exec -it so-elastalert bash -c "elastalert-test-rule $rulename $options" > $filesavelocation
	else
		docker exec -it so-elastalert bash -c "elastalert-test-rule $rulename $options"
	fi
}

rule_prompt(){
	current_rules=$(sudo ls /etc/elastalert/rules/)
        echo
        echo "This script will allow you to test an Elastalert rule."
        echo
        echo "Below is a list of active rules in the /etc/elastalert/rules/ directory."
        echo
        echo "$current_rules"
        echo
        echo "Note: To test a rule it must be accessible by the Elastalert docker container."
        echo
        echo "Please enter the file path and rule name you want to test."
        read -e rulename
}

log_save_prompt(){
	echo "The results can be rather long.  Would you like to write the results to a file? (Y/N)"
        read resultstolog
}

log_path_prompt(){
	echo "Please enter the file path and file name."
        read -e filesavelocation
        echo "Depending on the rule this may take a while."
}

if [ $skip -ne 1 ]; then
	rule_prompt
	log_save_prompt
        if [ ${resultstolog,,} = "y" ] ; then
		log_path_prompt
        fi
fi

docker_exec

if [ $? -eq 0 ]; then
	echo "Test completed successfully!"
        echo
else
	echo "Something went wrong..."
        echo
fi
