#!/bin/bash

. /usr/sbin/so-elastic-common

if [ "${KIBANA_ENABLED}" = "no" ]; then

	echo "Kibana is disabled, skipping config"

else

	# Load dashboards and index patterns first
	. /usr/sbin/so-elastic-configure-kibana-dashboards

	# Then set default index pattern and other config
	. /usr/sbin/so-elastic-configure-kibana-config

	# Finally, fix all shortcuts
	. /usr/sbin/so-elastic-configure-kibana-shortcuts

fi
