#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-common-status

# If Elasticsearch is not enabled, then exit immediately
[ "$ELASTICSEARCH_ENABLED" != "yes" ] && exit

echo -ne "${BLUE_BOLD}Status: Elastic stack${NORMAL}"
echo

/usr/sbin/so-elasticsearch-status

/usr/sbin/so-logstash-status

/usr/sbin/so-kibana-status

/usr/sbin/so-freqserver-status

/usr/sbin/so-domainstats-status

/usr/sbin/so-curator-status

/usr/sbin/so-elastalert-status

/usr/sbin/so-redis-status

echo
