#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

# If ufw is active, add firewall rules to DOCKER-USER and ensure they will persist after reboot
if [ -x /usr/sbin/ufw ] && /usr/sbin/ufw status | grep -q "Status: active"; then
	# We need to ensure proper rules are in place in the running firewall before starting containers
	if ! iptables -L DOCKER-USER -v | grep -q DROP.*all.*\!docker0.*docker0; then 
		# First, we need to insert the DROP rule at the top of DOCKER-USER
		iptables -I DOCKER-USER ! -i docker0 -o docker0 -j DROP
		# Next, we need to insert the stateful rule right above the DROP rule
		iptables -I DOCKER-USER ! -i docker0 -o docker0 -m state --state RELATED,ESTABLISHED -j ACCEPT
	fi

	# We need to ensure proper rules are in place after reboot before starting containers
	if ! grep -q "DOCKER-USER" /etc/ufw/after.rules; then	
		# First, we need to add DOCKER-USER to the filter section like this:
		# :ufw-after-forward - [0:0]
		# :DOCKER-USER - [0:0]
		sed -i '/:ufw-after-forward/a :DOCKER-USER - [0:0]' /etc/ufw/after.rules
		# Next, we need to add lines like this:
		# # Configure Docker rules
		# # /usr/sbin/so-allow will add new rules here for access to ports exposed by Docker containers
		# -A DOCKER-USER ! -i docker0 -o docker0 -m state --state RELATED,ESTABLISHED -j ACCEPT
		# -A DOCKER-USER ! -i docker0 -o docker0 -j DROP
		sed -i "/BROADCAST/{N;s/$/\n# Configure Docker rules\n# \/usr\/sbin\/so-allow will add new rules here for access to ports exposed by Docker containers\n-A DOCKER-USER ! -i docker0 -o docker0 -m state --state RELATED,ESTABLISHED -j ACCEPT\n-A DOCKER-USER ! -i docker0 -o docker0 -j DROP\n/}" /etc/ufw/after.rules
	fi
fi
