#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

LOG="/var/log/elasticsearch/$(hostname).log"

#########################################
# Options
#########################################
usage()
{
cat <<EOF
Start Elasticsearch
  Options:
  -h         This message
  -v         Tail the Elasticsearch log after starting

EOF
}

while getopts "h:v" OPTION
do
        case $OPTION in
                h)
                        usage
                        exit 0
                        ;;
                v)
                        TAIL=1
                        ;;
                *)
                        usage
                        exit 0
                        ;;
        esac
done

if [ "$ELASTICSEARCH_ENABLED" = "yes" ]; then
        echo -n "so-elasticsearch: "

        if docker ps | grep -q so-elasticsearch; then
                echo "Already started!"
        else
		docker rm so-elasticsearch >/dev/null 2>&1
		# Publish ports to $ELASTICSEARCH_PUBLISH_IP (127.0.0.1 by default)
                docker run --name=so-elasticsearch \
                        --detach \
                        --env "bootstrap.memory_lock=true" \
                        --env "cluster.name=$HOSTNAME" \
                        --env "http.host=0.0.0.0" \
                        --env "transport.host=127.0.0.1" \
                        --publish $ELASTICSEARCH_PUBLISH_IP:9200:9200 \
                        --publish $ELASTICSEARCH_PUBLISH_IP:9300:9300 \
                        --ulimit memlock=-1:-1 \
                        --ulimit nofile=65536:65536 \
                        --ulimit nproc=4096 \
                        --volume /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro \
                        --volume /etc/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro \
                        --volume /etc/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro \
                        --volume /nsm/elasticsearch:/usr/share/elasticsearch/data \
                        --volume /var/log/elasticsearch:/var/log/elasticsearch \
                        $ELASTICSEARCH_OPTIONS \
                        $DOCKERHUB/so-elasticsearch

		# Other containers will connect to Elasticsearch over $DOCKERNET
		docker network connect --alias elasticsearch $DOCKERNET so-elasticsearch
        	
		# Tail log if -v option provided
                if [[ "$TAIL" == 1 ]]; then
                        tail -f $LOG
                fi
	fi
fi
