#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

MYSQL="mysql --defaults-file=/etc/mysql/debian.cnf -sN"
EXPORT="/nsm/export"
BRO="$EXPORT/bro"

if [ "$#" -ne 1 ]; then
# Obligatory warning and disclaimers
cat << EOF 
This QUICK and DIRTY script should export logs from ELSA into log files that you can search using standard tools and/or import into Elasticsearch.

Exported log files will be written to $EXPORT.

WARNINGS AND DISCLAIMERS
* this script has NO error checking
* make sure you have plenty of free disk space as this is essentially duplicating all your logs
* this script has had very little testing
* this script is TOTALLY UNSUPPORTED!
* If this breaks your system, you get to keep both pieces!
* Use of this script may result in nausea, vomiting, or a burning sensation.
 
Once you've read all of the WARNINGS AND DISCLAIMERS above, please type AGREE to proceed:
EOF
read INPUT
if [ "$INPUT" != "AGREE" ] ; then exit 0; fi
fi

mkdir -p $BRO
cd $EXPORT

for table_name in `$MYSQL -Dsyslog_data -e 'show tables where Tables_in_syslog_data like "syslogs_index_%";'`; do
	echo "Processing table $table_name"
	for class_id in `$MYSQL -Dsyslog_data -e "select class_id from $table_name group by class_id;"`; do
		#class_name=`$MYSQL -Dsyslog -e "select class from classes where id = $class_id;" | sed 's|BRO_||g' | tr '[:upper:]' '[:lower:]'`
		class_name=`$MYSQL -Dsyslog -e "select class from classes where id = $class_id;" | tr '[:upper:]' '[:lower:]'`
		echo "Processing class $class_name"
		$MYSQL -Dsyslog_data -e "select msg from syslogs_index_1 where class_id = $class_id;" | sed 's/|/\t/g' >> $class_name.log
	done
done

for bro_log in bro_*; do
	log=$(echo $bro_log | cut -d_ -f2)
	echo "Moving $bro_log to bro/$log"
	mv $bro_log bro/$log
done

cat << EOF
If you would like to import these logs into Elastic, you can move them to /nsm/import/.

However, please be aware of a few things:

* Make sure you have plenty of free disk space as this is creating yet another copy of these logs.
* Logstash parsers only support the current version of Bro.  Older Bro logs may not be parsed properly.
EOF
