#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

BRO="/opt/bro/share/bro"

LOCALBRO="${BRO}/site/local.bro"

if [ -f ${LOCALBRO} ] ; then

	# If Bro hasn't already been configured to output JSON,
	# then we need to configure it and restart Bro.
	# We also need to handle the case where folks have
	# manually disabled JSON by commenting out the @load line.
	if ! grep "@load json-logs" ${LOCALBRO} >/dev/null 2>&1; then 

		header "Configuring Bro to output in JSON"

		cp -av ${SRC}/opt/bro/share/bro/json-logs ${BRO}

cat << EOF >> ${LOCALBRO}

# Output logs in JSON format
@load json-logs
EOF

		if [ "${BRO_ENABLED}" = "yes" ]; then
			/usr/sbin/nsm_sensor_ps-restart --only-bro
		fi
	fi
fi
