#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common
. /etc/nsm/securityonion.conf

# If Elasticsearch is not enabled, then exit immediately
[ "$ELASTICSEARCH_ENABLED" != "yes" ] && exit

SKIP=0

#########################################
# Options
#########################################
usage()
{
cat <<EOF
Security Onion Logstash - Clear Queue
  Options:
  -h         This message
  -y         Skip interactive mode
EOF
}

while getopts "h:y" OPTION
do
	case $OPTION in
		h)
			usage
			exit 0
			;;
		y)
			SKIP=1
			;;
		*)
			usage
			exit 0
			;;
	esac
done

if [ $SKIP -ne 1 ]; then
	# List queue data/files
	echo
	ls /nsm/logstash/queue/main/
	echo

	# Inform user we are about to delete all data
	echo
	echo "This script will delete all data in the Logstash processing queue."
	echo
	echo "If you would like to proceed, please type "AGREE" and hit ENTER."
	echo

	# Read user input
	read INPUT
	if [ "$INPUT" != "AGREE" ] ; then exit 0; fi
fi
# Stop Logstash
echo
docker stop so-logstash
echo

# Delete data
echo "Deleting data..."
rm /nsm/logstash/queue/main/* > /dev/null 2>&1

# Start Logstash and other services if not already started
echo
so-elastic-start
echo

# Message to user
echo
echo "All Logstash queue data has been deleted."
echo
