#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

for FILE in /etc/nsm/securityonion.conf /etc/nsm/sensortab; do
	if [ ! -f $FILE ]; then
		echo "$FILE not found!  Exiting!"
		exit 1
	fi
done

. /usr/sbin/so-elastic-configure-network

. /usr/sbin/so-elastic-configure-stack

. /usr/sbin/so-elastic-configure-apache

. /usr/sbin/so-elastic-configure-disable-elsa

. /usr/sbin/so-elastic-configure-syslog-ng

cd $ELASTICDIR

. /usr/sbin/so-elastic-configure-curator

. /usr/sbin/so-elastic-configure-elastalert

. /usr/sbin/so-elastic-configure-cron

. /usr/sbin/so-elastic-configure-bro

echo
echo "All Done!"
