#!/bin/bash

. /usr/sbin/so-common

ELASTICDIR="/opt/elastic"
mkdir -p $ELASTICDIR
cd $ELASTICDIR
SRC="$ELASTICDIR/src"

DOCKERHUB="securityonionsolutions"

ELASTICDOWNLOADCONF="/etc/nsm/elasticdownload.conf"
if ! grep "# Elastic Download" $ELASTICDOWNLOADCONF >/dev/null 2>&1; then
cat << EOF >> $ELASTICDOWNLOADCONF
# Our docker images are hosted on Docker Hub:
# https://hub.docker.com/u/securityonionsolutions/
DOCKERHUB="$DOCKERHUB"
EOF
fi

[ -f $ELASTICDOWNLOADCONF ] && . $ELASTICDOWNLOADCONF
