#!/bin/bash

. /usr/sbin/so-elastic-common

. /etc/nsm/securityonion.conf

if [ "$FREQ_SERVER_ENABLED" = "yes" ]; then
        echo -n "so-freqserver: "
        if docker ps | grep -q so-freqserver; then
                echo "Already started!"
        else
		docker rm so-freqserver >/dev/null 2>&1
		# Does not need to publish any ports
                docker run --name=so-freqserver \
                        --detach \
                        --volume /var/log/freq_server:/var/log/freq_server \
                        $FREQ_SERVER_OPTIONS \
                        $DOCKERHUB/so-freqserver

		# Logstash will connect to freqserver over $DOCKERNET
		docker network connect --alias freqserver $DOCKERNET so-freqserver
        fi
fi

