#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#########################################
# Options
#########################################
usage()
{
cat <<EOF
Restart Logtash
  Options:
  -h         This message
  -v         Tail the Logstash log after starting

EOF
}

while getopts "hv" OPTION
do
        case $OPTION in
                h)
                        usage
                        exit 0
                        ;;
                v)
                        TAIL=1
                        ;;
                *)
                        usage
                        exit 0
                        ;;
        esac
done

/usr/sbin/so-logstash-stop
if [[ "$TAIL" == 1 ]]; then
	/usr/sbin/so-logstash-start -v
else
	/usr/sbin/so-logstash-start
fi
