#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-common-status

if [ "$LOGSTASH_ENABLED" = "yes" ]; then
       QUEUE_TYPE=$(curl -s "$LOGSTASH_HOST:$LOGSTASH_PORT/_node/stats" | jq .pipelines.main.queue.type | sed s/\"//g)
       EVENTS_IN=$(curl -s "$LOGSTASH_HOST:$LOGSTASH_PORT/_node/stats" | jq .events.in)
       EVENTS_OUT=$(curl -s "$LOGSTASH_HOST:$LOGSTASH_PORT/_node/stats" | jq .events.out)
       echo -ne "  ${BLUE}*${NORMAL} so-logstash"
       if docker ps |  grep -q so-logstash; then
               if [ "$QUEUE_TYPE" == "memory" ] || [ "$QUEUE_TYPE" == "persisted" ] && [ "$EVENTS_IN" -ge 1 ] && [ "$EVENTS_OUT" -ne 0 ]; then
                       ok
               else
                   if curl -s "$LOGSTASH_HOST:$LOGSTASH_PORT" >/dev/null 2>&1; then
                        echo
                        echo "      Logstash has started, but is still initializing...$(warn)"
                        echo "      $EVENTS_IN events in queue, $EVENTS_OUT events published..."
                   else
                        echo
                        echo "    Logstash API/stats not yet available...still initializing.$(warn)"
                   fi
               fi
       else
               fail
       fi
fi

