#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /usr/sbin/so-elastic-common

if [ ! -f /etc/nsm/sensortab ]; then
	echo "No /etc/nsm/sensortab.  Exiting!"
	exit 1
fi

NUM_INTERFACES=`grep -v "^#" /etc/nsm/sensortab | wc -l`
if [ $NUM_INTERFACES -eq 0 ]; then
	echo "No enabled interfaces in /etc/nsm/sensortab.  Exiting!"
	exit 1
fi

header "Replaying pcaps to create logs for testing"
INTERFACE=`grep -v "^#" /etc/nsm/sensortab | head -1 | awk '{print $4}'`
for i in /opt/samples/*.pcap /opt/samples/markofu/*.pcap /opt/samples/mta/*.pcap /opt/samples/bro/*.trace /opt/samples/bro/*.pcap /opt/samples/bro/*/*.trace /opt/samples/bro/*/*.pcap; do
	echo -n "." 
	tcpreplay -i $INTERFACE -M10 $i >/dev/null 2>&1
done
echo
