#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source /usr/sbin/so-elastic-common

header "Sguil user accounts"
/usr/sbin/nsm_server_user-list

if [ -f /etc/elasticsearch/elasticsearch_accounts ]; then
	echo
	header "Elastic user accounts"
	so-elasticsearch-query _xpack/security/user 2>/dev/null| jq '.' |grep username |cut -d\" -f4
fi
