#!/bin/bash
#
# Copyright 2014,2015,2016,2017,2018,2019 Security Onion Solutions, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source /usr/sbin/so-elastic-common

if [ -f /etc/elasticsearch/elasticsearch_accounts ]; then
	echo "Since you have Elastic auth enabled, Elastic/Kibana accounts can be managed in Kibana via Management-->Users."
	echo
	echo "If you want to change the password for a Sguil/Squert account, press Enter to continue or Ctrl-c to cancel."
	read input
fi

/usr/sbin/nsm_server_user-passwd
